name: website-stalker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '7 * * * *' # once per hour at minute 7

permissions:
  contents: write

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    env:
      WEBSITE_STALKER_FROM: ${{ secrets.WEBSITE_STALKER_FROM }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_TARGET_CHAT: ${{ secrets.TELEGRAM_TARGET_CHAT }}
      TELEGRAM_DISABLE_WEB_PAGE_PREVIEW: true
    steps:
      - uses: EdJoPaTo/website-stalker-github-action@v1

      - uses: actions/checkout@v3

      - name: Check website-stalker config
        run: website-stalker check

      - name: Run website-stalker
        run: website-stalker run --all --commit

      - name: Push to Prowl
        run: curl --data "{\"apikey\": \"todo\", \"description\": \"todo\"}" "https://api.prowlapp.com/publicapi/add"

      - if: always()
        run: git push

